version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=vehicles
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for MySQL to be ready...' &&
        while ! nc -z mysql 3306; do
          sleep 1
        done &&
        echo 'MySQL is ready!' &&
        ./main
      "

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=vehicles
      - MYSQL_MAX_ALLOWED_PACKET=64M
    command: >
      --default-authentication-plugin=mysql_native_password
      --max-allowed-packet=64M
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data: 